### ISSUE TITLE
"list index out of range" when running separate ganache.py. Need more accounts?

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#130]
The README has:
```
In tsp run, it will dump all the ganache txs to stdout. To make this cleaner, open a new terminal and:
...
#run ganache.py. It calls ganache cli and fills in many arguments for you.
./ganache.py
```

If I run those lines, followed by:
```
#simulate 'scheduler' netlist, sending results to 'outdir_csv'
tsp run netlists/scheduler/netlist.py outdir_csv
```

Then it will crash with the following traceback:
```
tsp run netlists/scheduler/netlist.py outdir_csv
Attached to local RPC client listening at '127.0.0.1:8545'...
Traceback (most recent call last):
  File "./tsp", line 12, in <module>
    from engine.SimEngine import SimEngine
  File "/home/trentmc/code/tokenspice/engine/SimEngine.py", line 7, in <module>
    from util.constants import S_PER_MIN, S_PER_HOUR, S_PER_DAY, S_PER_MONTH, S_PER_YEAR
  File "/home/trentmc/code/tokenspice/util/constants.py", line 24, in <module>
    GOD_ACCOUNT = brownie.network.accounts[9]
  File "/home/trentmc/code/tokenspice/venv/lib/python3.8/site-packages/brownie/network/account.py", line 115, in __getitem__
    return self._accounts[key]
IndexError: list index out of range
```

The problem is that it it's looking for accounts[9] in brownie and that doesn't seem to be created. This is the thing to fix. Probably need to add more accounts for ganache.py setup.

**Comment by trentmc** [comment]
Full output when starting up a separate ganache.py. Note that only 3 accounts are created.
```console
trentmc@trentmcLnv:~$ cd code/tokenspice/
trentmc@trentmcLnv:~/code/tokenspice$ source venv/bin/activate
(venv) trentmc@trentmcLnv:~/code/tokenspice$ ./ganache.py
Ganache CLI v6.12.2 (ganache-core: 2.13.2)

Available Accounts
==================
(0) 0x66aB6D9362d4F35596279692F0251Db635165871 (100 ETH)
(1) 0x33A4622B82D4c04a53e170c638B944ce27cffce3 (100 ETH)
(2) 0xc920aBcE3Adb7A54ce740D7EE39Cf023d99e7da2 (100 ETH)

Private Keys
==================
(0) 0xbbfbee4961061d506ffbb11dfea64eba16355cbf1d9c29...
(1) 0x804365e293b9fab9bd11bddd39082396d56d30779efbb...
(2) 0x904365e293b9fab9bd11bddd39082396d56d30779efbb...

Gas Price
==================
1

Gas Limit
==================
10000000000

Call Gas Limit
==================
9007199254740991

Listening on 127.0.0.1:8545
```

**Comment by dinpran** [comment]
i am also haviing same problem have you got the answer

**Comment by trentmc** [comment]
I had fixed it via the commit https://github.com/tokenspice/tokenspice/commit/702848c0c9c0a10ab71dc1525b79ede140c12eb4

I just double-checked. It works.

1. Running `ganache.py`, it does indeed give me 10 accounts (see below)
2. And the code itself clearly adds the accounts (see further below)

Details for 1: from console:
```text
(venv) trentmc@trentmcLnv:~/code/tokenspice$ ./ganache.py 
Ganache CLI v6.12.2 (ganache-core: 2.13.2)

Available Accounts
==================
(0) 0x66aB6D9362d4F35596279692F0251Db635165871 (100 ETH)
(1) 0x33A4622B82D4c04a53e170c638B944ce27cffce3 (100 ETH)
(2) 0xc920aBcE3Adb7A54ce740D7EE39Cf023d99e7da2 (100 ETH)
(3) 0xCc10E5fc80ca5245f8E88F07C8f25956166fAb97 (100 ETH)
(4) 0xC251a8A9920544e8c0FbD8AA65857Ec1dB00f2DD (100 ETH)
(5) 0x06022629d7Fd960585d3B33f1d53c86a969a2493 (100 ETH)
(6) 0x962C196fdE6998744c69939213D47eEE071d6b0a (100 ETH)
(7) 0x6Ea526f5B81822CBFE166E4FbBa2752A42597D04 (100 ETH)
(8) 0xC11398eFF1F1382074790EeB80053E09B15EF4CF (100 ETH)
(9) 0x330997E70b83f1a562490FCaA5996314fA5a971a (100 ETH)

Private Keys
==================
(0) ...
```

Details for (2): in `ganache.py` file:
```python
ganache_command = f'ganache-cli --port {port_number} --gasLimit 10000000000 --gasPrice 1 ---hardfork istanbul --account="{alice_private_key},{amount_wei}" --account="{bob_private_key},{amount_wei}" --account="{factory_deployer_private_key},{amount_wei}"'  # pylint: disable=line-too-long

# add 7 more accounts, for 10 total. Private keys were chosen arbitrarily.
for private_key in [
    "0x69a0315f0a6932ca52d5b1ad9ce31b2fef7de658f8da625a6d97f4dbb3ba22c1",
    "0x2c06b48c205efccc3506430212630a11bcc99cad1994452898e5df63985eda10",
    "0xd890fedd404c6f49daf4be91cd720df22786e1d35d579b8372cc531eed80a267",
    "0x9da43e9603043299cd6c5aecec69b7713342496f3465caaadbee5db955f18010",
    "0x53a2a4124387132ceae955edb80f13aa549f2e956d3f8aae0383412a3c765a93",
    "0x1803ea57835da6f03f8b43458482f65f280600c278947fe0eaf78c5d7d260c81",
    "0xb13f2706716d269a9639f2eb99d38ba8aaef0e210d1b35a2e40e3e8b62ab76f9",
]:
    ganache_command += f' --account="{private_key},{amount_wei}"'

if args.run_in_background:
    os.system(ganache_command + "&")
else:
    os.system(ganache_command)
```

**Comment by trentmc** [comment]
> i am also haviing same problem have you got the answer

Therefore my question for you: do you have an up-to-date version of tokenspice? ie have you done a `git pull` in your tokenspice directory, and are in `main` branch? Or if you're in your own branch, have you merged in the fix from main into your branch?

I'll re-close this issue, since it was fixed; if you still find issues after my Q's above, please comment here and we can re-visit this issue. Thanks!
