### ISSUE TITLE
Error running pytest: "TypeError: required field "lineno" missing from alias"

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#171]
I just went through the README installation etc, up to where I run pytest:
```console
pytest sol057/contracts/simpletoken/test/test_Simpletoken.py::test_transfer
```

Running the above gives me: `TypeError: required field "lineno" missing from alias`

### Full traceback

```text
(venv) trentmc@trentmc-xps:~/code/tokenspice$ pytest sol057/contracts/simpletoken/test/test_Simpletoken.py::test_transfer
Traceback (most recent call last):
  File "/home/trentmc/code/tokenspice/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 180, in console_main
    code = main()
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 136, in main
    config = _prepareconfig(args, plugins)
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 313, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/_pytest/helpconfig.py", line 99, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 932, in pytest_cmdline_parse
    self.parse(args)
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1204, in parse
    self._preparse(args, addopts=addopts)
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1097, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 161, in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
  File "/home/trentmc/code/tokenspice/venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 360, in _rewrite_test
    co = compile(tree, fn_, "exec", dont_inherit=True)
TypeError: required field "lineno" missing from alias
```

**Comment by trentmc** [comment]
The fix is to force pytest >= 6.2.5
https://github.com/pytest-dev/pytest/discussions/9195
