### ISSUE TITLE
Issue with UnitTest & Simulating with TokenSPICE

### ISSUE THREAD

**Issue by dawidkubas** [tokenspice/tokenspice#183]
Hey, 

I have a problem with Unit Test and in the results with Simulating with TokenSPICE. I run ./ganache.py in the second terminal, successful compiled all contract and this code: 

```
#run single test. It uses brownie, which auto-starts Ganache local blockchain node.
pytest sol057/contracts/simpletoken/test/test_Simpletoken.py::test_transfer

#run all of a directory's tests
pytest sol057/contracts/simpletoken/test

#run all unit tests
pytest

#run static type-checking. By default, uses config mypy.ini. Note: pytest does dynamic type-checking.
mypy ./

#run linting on code style
pylint *

#auto-fix some pylint complaints
black ./ 
```
Running single test and running all of a directory's tests works correctly but when runs All unit tests I have a lot of ValueError: insufficient funds for gas * price + value. 

Example: 
```
______________________________________________________________ test_ethFunding _______________________________________________________________

    def test_ethFunding():
        # ensure each account has exactly 30 ETH
        for account in [account0, account1, account2]:
>           transferETH(account, GOD_ACCOUNT, account.balance())

sol080/contracts/scheduler080/test/test_VestingWallet080.py:61: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
util/tx.py:22: in transferETH
    return from_account.transfer(
venv/lib/python3.9/site-packages/brownie/network/account.py:644: in transfer
    receipt, exc = self._make_transaction(
venv/lib/python3.9/site-packages/brownie/network/account.py:752: in _make_transaction
    exc = VirtualMachineError(e)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = VirtualMachineError(ValueError({'message': 'insufficient funds for gas * price + value', 'stack': 'Error: insufficient...at TransactionPool.prepareTransaction (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:187809)', 'code': -32003}))
exc = {'code': -32003, 'message': 'insufficient funds for gas * price + value', 'stack': 'Error: insufficient funds for gas * price + value\n    at TransactionPool.prepareTransaction (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:187809)'}

    def __init__(self, exc: ValueError) -> None:
        self.txid: str = ""
        self.source: str = ""
        self.revert_type: str = ""
        self.pc: Optional[int] = None
        self.revert_msg: Optional[str] = None
        self.dev_revert_msg: Optional[str] = None
    
        try:
            exc = exc.args[0]
        except Exception:
            pass
    
        if not (isinstance(exc, dict) and "message" in exc):
            raise ValueError(str(exc)) from None
    
        if "data" not in exc:
>           raise ValueError(exc["message"]) from None
           ValueError: insufficient funds for gas * price + value

venv/lib/python3.9/site-packages/brownie/exceptions.py:96: ValueError
```
And the results summary look like: 

```
========================================================== short test summary info ===========================================================
FAILED agents/test/test_PublisherAgent.py::test_createPoolAgent[False] - ValueError: insufficient funds for gas * price + value
FAILED agents/test/test_PublisherAgent.py::test_createPoolAgent[True] - ValueError: insufficient funds for gas * price + value
FAILED agents/test/test_PublisherAgent.py::test_unstakeOCEANsomewhere[False] - ValueError: insufficient funds for gas * price + value
FAILED agents/test/test_PublisherAgent.py::test_unstakeOCEANsomewhere[True] - ValueError: insufficient funds for gas * price + value
FAILED agents/test/test_PublisherAgent.py::test_sellDTsomewhere[False] - ValueError: insufficient funds for gas * price + value
FAILED agents/test/test_PublisherAgent.py::test_sellDTsomewhere[True] - ValueError: insufficient funds for gas * price + value
FAILED agents/test/test_VestingFunderAgent.py::test1 - ValueError: insufficient funds for gas * price + value
FAILED engine/test/test_AgentBase.py::testReceiveAndSend[True] - ValueError: insufficient funds for gas * price + value
FAILED engine/test/test_AgentWallet.py::testOCEAN[AgentWalletEvm] - ValueError: insufficient funds for gas * price + value
FAILED engine/test/test_AgentWallet.py::testFloatingPointRoundoff_OCEAN[AgentWalletEvm] - ValueError: insufficient funds for gas * price + ...
FAILED engine/test/test_AgentWallet.py::test_transferOCEAN[AgentWalletEvm] - ValueError: insufficient funds for gas * price + value
FAILED netlists/scheduler/test/test_netlist.py::test_SimState - ValueError: insufficient funds for gas * price + value
FAILED netlists/simplepool/test/test_netlist.py::test_SimState - ValueError: insufficient funds for gas * price + value
FAILED sol057/contracts/scheduler057/test/test_VestingWallet057.py::test_ethFunding - ValueError: insufficient funds for gas * price + value
FAILED sol080/contracts/scheduler080/test/test_VestingWallet080.py::test_ethFunding - ValueError: insufficient funds for gas * price + value
ERROR agents/test/test_DataconsumerAgent.py::test_doBuyAndConsumeDT_happy_path - ValueError: insufficient funds for gas * price + value
ERROR agents/test/test_DataconsumerAgent.py::test_doBuyAndConsumeDT_have_rugged_pools - ValueError: insufficient funds for gas * price + value
ERROR agents/test/test_DataconsumerAgent.py::test_buyAndConsumeDT - ValueError: insufficient funds for gas * price + value
ERROR agents/test/test_PoolAgent.py::test1 - ValueError: insufficient funds for gas * price + value
ERROR agents/test/test_SpeculatorAgent.py::test_doSpeculateAction[SpeculatorAgent] - ValueError: insufficient funds for gas * price + value
ERROR agents/test/test_SpeculatorAgent.py::test_doSpeculateAction[StakerspeculatorAgent] - ValueError: insufficient funds for gas * price +...
ERROR agents/test/test_SpeculatorAgent.py::test_speculateAction_with_rugged_pools[SpeculatorAgent] - ValueError: insufficient funds for gas...
ERROR agents/test/test_SpeculatorAgent.py::test_speculateAction_with_rugged_pools[StakerspeculatorAgent] - ValueError: insufficient funds f...
ERROR agents/test/test_SpeculatorAgent.py::test_speculateAction_with_good_pools[SpeculatorAgent] - ValueError: insufficient funds for gas *...
ERROR agents/test/test_SpeculatorAgent.py::test_speculateAction_with_good_pools[StakerspeculatorAgent] - ValueError: insufficient funds for...
ERROR agents/test/test_SpeculatorAgent.py::test_take_step[SpeculatorAgent] - ValueError: insufficient funds for gas * price + value
ERROR agents/test/test_SpeculatorAgent.py::test_take_step[StakerspeculatorAgent] - ValueError: insufficient funds for gas * price + value
ERROR engine/test/test_AgentBase.py::test_DT - ValueError: insufficient funds for gas * price + value
ERROR engine/test/test_AgentBase.py::test_BPT - ValueError: insufficient funds for gas * price + value
ERROR engine/test/test_AgentBase.py::test_stakeOCEAN - ValueError: insufficient funds for gas * price + value
ERROR engine/test/test_AgentBase.py::test_unstakeOCEAN - ValueError: insufficient funds for gas * price + value
ERROR engine/test/test_AgentWallet.py::test_DT - ValueError: insufficient funds for gas * price + value
ERROR engine/test/test_AgentWallet.py::test_BPT - ValueError: insufficient funds for gas * price + value
ERROR engine/test/test_AgentWallet.py::test_poolToDTaddress - ValueError: insufficient funds for gas * price + value
ERROR engine/test/test_AgentWallet.py::test_sellDT - ValueError: insufficient funds for gas * price + value
ERROR engine/test/test_AgentWallet.py::test_buyDT - ValueError: insufficient funds for gas * price + value
ERROR engine/test/test_AgentWallet.py::test_stakeOCEAN - ValueError: insufficient funds for gas * price + value
ERROR engine/test/test_AgentWallet.py::test_unstakeOCEAN - ValueError: insufficient funds for gas * price + value
ERROR netlists/oceanv3/test/test_KPIs.py::test_get_OCEAN_in_DTs - ValueError: insufficient funds for gas * price + value
ERROR netlists/oceanv3/test/test_KPIs.py::test_get_OCEAN_in_BPTs - ValueError: insufficient funds for gas * price + value
```

And later when I want run: 
``` 
#run simulation, sending results to 'outdir_csv' (clear dir first, to be sure)
rm -rf outdir_csv; tsp run netlists/scheduler/netlist.py outdir_csv
```
I again get a this error: 
```
Arguments: NETLIST=netlists/scheduler/netlist.py, OUTPUT_DIR=outdir_csv, DO_PROFILE=False
/Users/dawid/Desktop/TokenSPICE/tokenspice/venv/lib/python3.9/site-packages/brownie/network/main.py:44: BrownieEnvironmentWarning: Development network has a block height of 65
  warnings.warn(
Attached to local RPC client listening at '127.0.0.1:8545'...
mnemonic: 'fatal debris prepare retreat club story ecology silver bar reject scare sustain'
mnemonic: 'give drift gate industry rescue dynamic cradle special dolphin strike shove clerk'
INFO:master:Begin.
INFO:master:SimStrategy={OCEAN_funded=5.0, duration_seconds=157680000, log_interval=7776000, max_ticks=122.66666666666667, start_timestamp=1731052548, time_step=2592000 /SimStrategy}

INFO:master:Tick=0 (0.0 h, 0.0 d, 0.0 mo, 0.0 y); timestamp=1699517482; OCEAN_vested=0.000000, OCEAN_released=0.000000; beneficiary_OCEAN=0.000000
Traceback (most recent call last):
  File "/Users/dawid/Desktop/TokenSPICE/tokenspice/tsp", line 260, in <module>
    do_main()
  File "/Users/dawid/Desktop/TokenSPICE/tokenspice/tsp", line 248, in do_main
    do_run()
  File "/Users/dawid/Desktop/TokenSPICE/tokenspice/tsp", line 84, in do_run
    engine.run()
  File "/Users/dawid/Desktop/TokenSPICE/tokenspice/engine/SimEngine.py", line 41, in run
    self.takeStep()
  File "/Users/dawid/Desktop/TokenSPICE/tokenspice/engine/SimEngine.py", line 59, in takeStep
    self.state.takeStep()
  File "/Users/dawid/Desktop/TokenSPICE/tokenspice/engine/SimStateBase.py", line 24, in takeStep
    agent.takeStep(self)
  File "/Users/dawid/Desktop/TokenSPICE/tokenspice/agents/VestingFunderAgent.py", line 43, in takeStep
    vw_contract = BROWNIE_PROJECT057.VestingWallet057.deploy(
  File "/Users/dawid/Desktop/TokenSPICE/tokenspice/venv/lib/python3.9/site-packages/brownie/network/contract.py", line 549, in __call__
    return tx["from"].deploy(
  File "/Users/dawid/Desktop/TokenSPICE/tokenspice/venv/lib/python3.9/site-packages/brownie/network/account.py", line 510, in deploy
    receipt, exc = self._make_transaction(
  File "/Users/dawid/Desktop/TokenSPICE/tokenspice/venv/lib/python3.9/site-packages/brownie/network/account.py", line 752, in _make_transaction
    exc = VirtualMachineError(e)
  File "/Users/dawid/Desktop/TokenSPICE/tokenspice/venv/lib/python3.9/site-packages/brownie/exceptions.py", line 96, in __init__
    raise ValueError(exc["message"]) from None
ValueError: insufficient funds for gas * price + value
(venv) (base) FAIL
```

Do you have any idea what could be causing this error? 
Thank you

**Comment by trentmc** [comment]
Thanks for trying out TokenSPICE! And thanks for the thorough error report.

It's likely because the gas priority fee was not specified, which Ganache needs as part of the EIP1559 updates.

We had the same issue in ocean.py, e.g. [issue#1089](https://github.com/oceanprotocol/ocean.py/issues/1089) and [elsewhere](https://github.com/search?q=repo%3Aoceanprotocol%2Focean.py+insufficient+funds&type=issues).

[Here's the PR that fixed it](https://github.com/oceanprotocol/ocean.py/pull/1090/files).

Wanna try that? Ideally via a PR. I'll be happy to review and merge.

**Comment by dawidkubas** [comment]
Thanks for your answer. 

Unfortunately, I am not sure where I should implant the changes that are shown in the PRs you sent. 
Could you please indicate where to make [this change](https://github.com/oceanprotocol/ocean.py/pull/1090/files)

I will be very grateful.

**Comment by trentmc** [comment]
> Thanks for your answer.
> 
> Unfortunately, I am not sure where I should implant the changes that are shown in the PRs you sent. Could you please indicate where to make [this change](https://github.com/oceanprotocol/ocean.py/pull/1090/files)
> 
> I will be very grateful.

You can try changes in https://github.com/tokenspice/tokenspice/blob/main/util/tx.py

And do run tests. It will help you to iterate quickly. https://github.com/tokenspice/tokenspice#-running-debugging

FYI I'm not actively maintaining this code. Too many other things:( . But I am happy to help guide you as you work on this.
